name: "Build and Test virtual routers"

on:
  pull_request:
  push:
    branches:
      - main
      - master

env:
  PNS: ci-${GITHUB_RUN_ID}

jobs:
  test_matrix:
    runs-on: ["self-hosted"]
    container:
      image: vrnetlab/ci-builder
      volumes:
        - /data/gh-runner/vrnetlab-images:/vrnetlab-images
    strategy:
      matrix:
        platform: ['csr', 'nxos', 'routeros', 'sros', 'veos', 'vmx', 'vqfx', 'vr-bgp', 'vr-xcon', 'vrp', 'vsr1000', 'xrv', 'xrv9k']

    steps:
      - uses: actions/checkout@v3
      - name: Build ${{ matrix.platform }}
        run: |
          cp /vrnetlab-images/${{ matrix.platform }}/* ${{ matrix.platform }} || true
          ls -al ${{ matrix.platform }}
          make ${{ matrix.platform }}
      - name: Test ${{ matrix.platform }}
        run: |
          make ${{ matrix.platform }}-test
